name: ArmorBuffs
version: 0.1.1
main: com.frostwoodmc.armorbuffs.ArmorBuffs
api-version: 1.21

commands:
  armorbuffs:
    description: ArmorBuffs admin command
    usage: /armorbuffs <reload|tag>
    permission: armorbuffs.admin

permissions:
  armorbuffs.admin:
    description: Basic Admin functions.
    default: op
