name: ArmorBuffs
version: 0.0.1
main: com.frostwoodmc.armorbuffs.ArmorBuffs
api-version: 1.21

commands:
  armorbuffs:
    description: Reload the ArmorBuffs config
    usage: /<command> reload
    permission: armorbuffs.reload

permissions:
  armorbuffs.reload:
    description: Allows reloading the plugin config
    default: op
